all:
	ctags -f eigen3.tags --tag-relative=yes --recurse=yes /usr/local/include/eigen3/
	ctags -f opencv.tags --tag-relative=yes --recurse=yes /usr/local/Cellar/opencv3/3.0.0/include/
	ctags -f mp_eos.tags --tag-relative=yes --recurse=yes --languages=c,c++ --exclude=thirdparty ~/dev/mp_vision/
